Disable CodeDeploy

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -1083,118 +1083,118 @@ jobs:
       - name: Create CloudFront invalidation
         run: aws cloudfront create-invalidation --distribution-id ${{ secrets.CLOUDFRONT_CDN_DISTRIBUTION_ID }} --paths "/*"
 
-  deploy-codedeploy:
-    name: Deploy using CodeDeploy
-    # if: ${{ env.AWS_ENABLED == 1 }}
-    # needs: [test-prod, test, test-dialyzer]
-    needs: [test, test-dialyzer]
-    permissions:
-      # Interact with GitHub OIDC Token endpoint for AWS
-      id-token: write
-      contents: read
-
-      # Push to ghcr.io repository
-      packages: write
-    runs-on: ubuntu-latest
-    environment: ${{ (github.ref_name == 'main' && 'staging') || (github.ref_name == 'qa' && 'qa') || (github.ref_name == 'prod' && 'production') }}
-    strategy:
-      fail-fast: false
-      matrix: ${{ fromJson(needs.setup-matrix.outputs.deploy-matrix) }}
-    env:
-      DOCKER_FILE: deploy/${{ matrix.os }}.Dockerfile
-      VAR: ${{ matrix.elixir }}-erlang-${{ matrix.otp }}-${{ matrix.os }}-${{ matrix.build_os_ver }}
-    steps:
-      - name: Log in to GHCR
-        uses: docker/login-action@v3
-        with:
-          registry: ghcr.io
-          username: ${{ github.actor }}
-          password: ${{ secrets.GITHUB_TOKEN }}
-
-      - name: Log in to Docker Hub
-        uses: docker/login-action@v3
-        with:
-          username: ${{ secrets.DOCKERHUB_USERNAME }}
-          password: ${{ secrets.DOCKERHUB_TOKEN }}
-
-      - name: Configure AWS credentials
-        if: ${{ env.AWS_ENABLED == 1 }}
-        uses: aws-actions/configure-aws-credentials@v4
-        # https://github.com/aws-actions/configure-aws-credentials
-        # https://docs.github.com/en/actions/deployment/security-hardening-your-deployments/configuring-openid-connect-in-amazon-web-services
-        with:
-          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
-          aws-region: ${{ vars.AWS_REGION }}
-
-      - name: Check out source
-        uses: actions/checkout@v4
-
-      - name: Set variables
-        id: vars
-        run: |
-          echo "GITHUB_SHA_SHORT=$(echo $GITHUB_SHA | cut -c 1-7)" >> $GITHUB_ENV
-
-      - name: Set up Docker buildx
-        id: buildx
-        uses: docker/setup-buildx-action@v3
-        with:
-          driver-opts: network=host
-
-      - name: Get build artifacts on host
-        uses: docker/build-push-action@v5
-        with:
-          file: ${{ env.DOCKER_FILE }}
-          target: artifacts
-          build-args: |
-            ELIXIR_VER=${{ matrix.elixir }}
-            OTP_VER=${{ matrix.otp }}
-            BUILD_OS_VER=${{ matrix.build_os_ver }}
-            PROD_OS_VER=${{ matrix.prod_os_ver }}
-          context: .
-          builder: ${{ steps.buildx.outputs.name }}
-          push: false
-          cache-from: type=gha,scope=${{ github.workflow }}-${{ env.VAR }}
-          outputs: type=local,dest=output
-
-      # - name: List output dir
-      #   run: find output -print
-
-      - name: Copy files
-        run: |
-          mkdir -p revision
-          cp -v appspec.yml revision
-          cp -v "output/_build/${{env.MIX_ENV}}/${{env.MIX_ENV}}-0.1.0.tar.gz" revision
-          mkdir -p revision/systemd
-          cp -v output/_build/${{env.MIX_ENV}}/systemd/lib/systemd/system/* revision/systemd
-          mkdir -p revision/bin
-          cp -v bin/* revision/bin
-          mkdir -p revision/etc
-
-      - name: List revision dir
-        run: find revision -type f -print
-
-      - name: Set variables
-        run: echo "REVISION_FILE=${{env.CODEDEPLOY_APPLICATION}}-$(date +'%Y%m%d%H%M%S')-${{env.GITHUB_SHA_SHORT}}.zip" >> $GITHUB_ENV
-        # run: echo "REVISION_FILE=${{env.CODEDEPLOY_APPLICATION}}-${{github.event.head_commit.timestamp}}-${{env.GITHUB_SHA_SHORT}}.zip" >> $GITHUB_ENV
-
-      - name: Create CodeDeploy revision
-        run: |
-          aws deploy push --application-name ${CODEDEPLOY_APPLICATION} \
-            --description "Bounce revision ${GITHUB_SHA_SHORT}" \
-            --s3-location s3://${{env.CODEDEPLOY_BUCKET}}/${{env.REVISION_FILE}} \
-            --source revision
-
-      - name: Create CodeDeploy deployment
-        run: |
-          aws deploy create-deployment --application-name ${{env.CODEDEPLOY_APPLICATION}} \
-            --deployment-group-name ${{env.CODEDEPLOY_DEPLOYMENT_GROUP}} \
-            --s3-location bucket=${{env.CODEDEPLOY_BUCKET}},key=${{env.REVISION_FILE}},bundleType=zip \
-            --description "Bounce revision ${{env.GITHUB_SHA_SHORT}}"
-
-      # - name: Set vars
-      #   run: aws deploy create-deployment \
-      #     --application-name ${{env.CODEDEPLOY_APPLICATION_NAME}} \
-      #     --deployment-group-name ${{env.CODEDEPLOY_DEPLOYMENT_GROUP_NAME}}
+  # deploy-codedeploy:
+  #   name: Deploy using CodeDeploy
+  #   # if: ${{ env.AWS_ENABLED == 1 }}
+  #   # needs: [test-prod, test, test-dialyzer]
+  #   needs: [test, test-dialyzer, setup-matrix]
+  #   permissions:
+  #     # Interact with GitHub OIDC Token endpoint for AWS
+  #     id-token: write
+  #     contents: read
+  #
+  #     # Push to ghcr.io repository
+  #     packages: write
+  #   runs-on: ubuntu-latest
+  #   environment: ${{ (github.ref_name == 'main' && 'staging') || (github.ref_name == 'qa' && 'qa') || (github.ref_name == 'prod' && 'production') }}
+  #   strategy:
+  #     fail-fast: false
+  #     matrix: ${{ fromJson(needs.setup-matrix.outputs.deploy-matrix) }}
+  #   env:
+  #     DOCKER_FILE: deploy/${{ matrix.os }}.Dockerfile
+  #     VAR: ${{ matrix.elixir }}-erlang-${{ matrix.otp }}-${{ matrix.os }}-${{ matrix.build_os_ver }}
+  #   steps:
+  #     - name: Log in to GHCR
+  #       uses: docker/login-action@v3
+  #       with:
+  #         registry: ghcr.io
+  #         username: ${{ github.actor }}
+  #         password: ${{ secrets.GITHUB_TOKEN }}
+  #
+  #     - name: Log in to Docker Hub
+  #       uses: docker/login-action@v3
+  #       with:
+  #         username: ${{ secrets.DOCKERHUB_USERNAME }}
+  #         password: ${{ secrets.DOCKERHUB_TOKEN }}
+  #
+  #     - name: Configure AWS credentials
+  #       if: ${{ env.AWS_ENABLED == 1 }}
+  #       uses: aws-actions/configure-aws-credentials@v4
+  #       # https://github.com/aws-actions/configure-aws-credentials
+  #       # https://docs.github.com/en/actions/deployment/security-hardening-your-deployments/configuring-openid-connect-in-amazon-web-services
+  #       with:
+  #         role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
+  #         aws-region: ${{ vars.AWS_REGION }}
+  #
+  #     - name: Check out source
+  #       uses: actions/checkout@v4
+  #
+  #     - name: Set variables
+  #       id: vars
+  #       run: |
+  #         echo "GITHUB_SHA_SHORT=$(echo $GITHUB_SHA | cut -c 1-7)" >> $GITHUB_ENV
+  #
+  #     - name: Set up Docker buildx
+  #       id: buildx
+  #       uses: docker/setup-buildx-action@v3
+  #       with:
+  #         driver-opts: network=host
+  #
+  #     - name: Get build artifacts on host
+  #       uses: docker/build-push-action@v5
+  #       with:
+  #         file: ${{ env.DOCKER_FILE }}
+  #         target: artifacts
+  #         build-args: |
+  #           ELIXIR_VER=${{ matrix.elixir }}
+  #           OTP_VER=${{ matrix.otp }}
+  #           BUILD_OS_VER=${{ matrix.build_os_ver }}
+  #           PROD_OS_VER=${{ matrix.prod_os_ver }}
+  #         context: .
+  #         builder: ${{ steps.buildx.outputs.name }}
+  #         push: false
+  #         cache-from: type=gha,scope=${{ github.workflow }}-${{ env.VAR }}
+  #         outputs: type=local,dest=output
+  #
+  #     # - name: List output dir
+  #     #   run: find output -print
+  #
+  #     - name: Copy files
+  #       run: |
+  #         mkdir -p revision
+  #         cp -v appspec.yml revision
+  #         cp -v "output/_build/${{env.MIX_ENV}}/${{env.MIX_ENV}}-0.1.0.tar.gz" revision
+  #         mkdir -p revision/systemd
+  #         cp -v output/_build/${{env.MIX_ENV}}/systemd/lib/systemd/system/* revision/systemd
+  #         mkdir -p revision/bin
+  #         cp -v bin/* revision/bin
+  #         mkdir -p revision/etc
+  #
+  #     - name: List revision dir
+  #       run: find revision -type f -print
+  #
+  #     - name: Set variables
+  #       run: echo "REVISION_FILE=${{env.CODEDEPLOY_APPLICATION}}-$(date +'%Y%m%d%H%M%S')-${{env.GITHUB_SHA_SHORT}}.zip" >> $GITHUB_ENV
+  #       # run: echo "REVISION_FILE=${{env.CODEDEPLOY_APPLICATION}}-${{github.event.head_commit.timestamp}}-${{env.GITHUB_SHA_SHORT}}.zip" >> $GITHUB_ENV
+  #
+  #     - name: Create CodeDeploy revision
+  #       run: |
+  #         aws deploy push --application-name ${CODEDEPLOY_APPLICATION} \
+  #           --description "Bounce revision ${GITHUB_SHA_SHORT}" \
+  #           --s3-location s3://${{env.CODEDEPLOY_BUCKET}}/${{env.REVISION_FILE}} \
+  #           --source revision
+  #
+  #     - name: Create CodeDeploy deployment
+  #       run: |
+  #         aws deploy create-deployment --application-name ${{env.CODEDEPLOY_APPLICATION}} \
+  #           --deployment-group-name ${{env.CODEDEPLOY_DEPLOYMENT_GROUP}} \
+  #           --s3-location bucket=${{env.CODEDEPLOY_BUCKET}},key=${{env.REVISION_FILE}},bundleType=zip \
+  #           --description "Bounce revision ${{env.GITHUB_SHA_SHORT}}"
+  #
+  #     # - name: Set vars
+  #     #   run: aws deploy create-deployment \
+  #     #     --application-name ${{env.CODEDEPLOY_APPLICATION_NAME}} \
+  #     #     --deployment-group-name ${{env.CODEDEPLOY_DEPLOYMENT_GROUP_NAME}}
 
   deploy-ecs:
     name: Deploy to AWS ECS
